#!/usr/bin/env python3
"""capture_router_task.py test harness — profile resolution + argv construction for the
deterministic capture-router stage shell (A25). Scratch; safe to delete."""
import json, os, sys, tempfile, shutil, subprocess

HARNESS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # .../engine/tools
sys.path.insert(0, HARNESS)
import capture_router_task as crt

PASS, FAIL = [], []
def check(name, cond):
    (PASS if cond else FAIL).append(name)
    print(("  ok  " if cond else " FAIL ") + name)

CONNECTORS = '''# generated by setup — fixture
notion:
  enabled: true
  mode: tactical                     # inline comment noise
vault:
  enabled: true
  live_kbs: ["alpha", "beta"]
  live_root: "TestVault"             # relative to env root
  live_kb_map:                       # kb key -> vault folder
    alpha: "01_Alpha"
    beta: "02_Beta"
gate:
  auto_ship_kbs: ["alpha"]
'''

DOMAINS = '''session_capture:
  evidence_dir: "X:/nowhere/raw/sessions"
  domain_map:                    # project -> kb
    someproject: alpha
    _default: beta
brief:
  default_scope: all
'''

d = tempfile.mkdtemp(prefix="crt_")
try:
    env_root = os.path.join(d, "envroot")
    os.makedirs(os.path.join(env_root, "profile"))
    open(os.path.join(env_root, "profile", "connectors.yaml"), "w", encoding="utf-8").write(CONNECTORS)
    open(os.path.join(env_root, "profile", "domains.yaml"), "w", encoding="utf-8").write(DOMAINS)

    # 1. yaml-subset parser: quoted values, inline comments, nesting, flow-lists skipped
    parsed = crt._parse_yaml_subset(CONNECTORS)
    check("parser: quoted value extracted", parsed["vault"]["live_root"] == "TestVault")
    check("parser: nested map extracted",
          parsed["vault"]["live_kb_map"] == {"alpha": "01_Alpha", "beta": "02_Beta"})
    check("parser: inline comment stripped from bare value",
          crt._parse_yaml_subset("a:\n  b: dev   # note\n")["a"]["b"] == "dev")

    # 2. read_profile resolves the three facts
    live_root, kb_map, default_kb = crt.read_profile(env_root)
    check("profile: live_root", live_root == "TestVault")
    check("profile: kb_map", kb_map == {"alpha": "01_Alpha", "beta": "02_Beta"})
    check("profile: default_kb from domain_map._default", default_kb == "beta")

    # 2b. A42: no `_default` -> fall back to a REAL kb from THIS install's map (sorted), never "dev".
    nodefault = "session_capture:\n  domain_map:\n    someproject: alpha\nbrief:\n  default_scope: all\n"
    open(os.path.join(env_root, "profile", "domains.yaml"), "w", encoding="utf-8").write(nodefault)
    _, kbm2, def2 = crt.read_profile(env_root)
    check("A42: no _default -> sorted(kb_map)[0], not a baked-in 'dev'",
          def2 == sorted(kbm2)[0] == "alpha" and def2 != "dev")
    open(os.path.join(env_root, "profile", "domains.yaml"), "w", encoding="utf-8").write(DOMAINS)  # restore

    # 3. build_argv: relative live_root joins env_root; no chrome without a Bookmarks file
    argv = crt.build_argv(env_root, live_root, kb_map, default_kb, 3)
    vault = os.path.join(env_root, "TestVault")
    check("argv: vault-root resolved under env_root",
          argv[argv.index("--vault-root") + 1] == vault)
    check("argv: one --kb flag per map entry", argv.count("--kb") == 2
          and "alpha=01_Alpha" in argv and "beta=02_Beta" in argv)
    check("argv: chrome omitted when no Bookmarks export", "chrome" not in argv)
    check("argv: default kb + manifest + context-log wired",
          argv[argv.index("--default-kb") + 1] == "beta"
          and argv[argv.index("--context-log") + 1].endswith("context-log.jsonl"))

    # 4. chrome source included when the Bookmarks export exists
    bm = os.path.join(vault, "00_Inbox", ".state", "chrome")
    os.makedirs(bm)
    open(os.path.join(bm, "Bookmarks"), "w").write("{}")
    argv2 = crt.build_argv(env_root, live_root, kb_map, default_kb, 3)
    check("argv: chrome + --bookmarks included when export exists",
          "chrome" in argv2 and "--bookmarks" in argv2)

    # 5. absolute live_root used as-is
    abs_root = os.path.join(d, "AbsVault")
    argv3 = crt.build_argv(env_root, abs_root, kb_map, default_kb, 3)
    check("argv: absolute live_root honored", argv3[argv3.index("--vault-root") + 1] == abs_root)

    # 6. CLI dry-run: --print-argv exits 0 and emits the JSON argv (no router execution)
    r = subprocess.run([sys.executable, os.path.join(HARNESS, "capture_router_task.py"),
                        "--env-root", env_root, "--print-argv"],
                       capture_output=True, text=True)
    check("CLI --print-argv exits 0 with a JSON argv",
          r.returncode == 0 and json.loads(r.stdout)[0] == "run")

    # 7. missing profile facts fail loud
    open(os.path.join(env_root, "profile", "connectors.yaml"), "w", encoding="utf-8").write("vault:\n  enabled: true\n")
    r2 = subprocess.run([sys.executable, os.path.join(HARNESS, "capture_router_task.py"),
                         "--env-root", env_root, "--print-argv"],
                        capture_output=True, text=True)
    check("missing live_root/kb_map fails loud (exit!=0, names setup)",
          r2.returncode != 0 and "setup" in (r2.stdout + r2.stderr))

    print(f"\n{len(PASS)} passed, {len(FAIL)} failed")
    if FAIL:
        print("FAILURES:", FAIL)
    sys.exit(1 if FAIL else 0)
finally:
    shutil.rmtree(d, ignore_errors=True)
